import { Input } from "./Input/input";
import styles from "./styles.module.scss";
import Head from "next/head";
export default function contact() {
  return (
    <div>
      <Head>
        <title>Contatti</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.png" />
      </Head>

      <div className={styles.formContainer}>
        <form className={styles.formWrapper}>
          <div className={styles.nameWrapper}>
            {/* <input
              className={styles.input}
              type="text"
              id="fname"
              name="firstname"
              placeholder="Il tuo nome..."
              required
            />

            <input
              className={styles.input}
              type="text"
              id="lname"
              name="lastname"
              placeholder="Il tuo cognome..."
              required
            /> */}
            <Input />
          </div>

          {/* <div className={styles.nameWrapper}>
            <input
              className={styles.input}
              type="email"
              id="email"
              name="email"
              placeholder="La tua email..."
              required
            />

            <select className={styles.select}>
              <option>Italia</option>
              <option>Russia</option>
              <option>Francia</option>
              <option>USA</option>
            </select>
          </div>

          <div className={styles.nameWrapper}>
            <textarea
              className={styles.textarea}
              id="subject"
              name="subject"
              placeholder="Scrivi qualcosa..."
            ></textarea>
          </div> */}

          <button className={styles.arrowBtn}>Invia</button>
        </form>
      </div>
    </div>
  );
}
