import styles from "./styles.module.scss";
import Head from "next/head";
export default function contact() {
  return (
    <div>
      <Head>
        <title>Ferdast.com</title>
        <meta name="description" content="Generated by create next app" />
        <link
          href="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.css"
          rel="stylesheet"
        />

        <link rel="icon" href="/favicon.png" />
      </Head>

      <div className={styles.formContainer}>
        <form className={styles.formWrapper}>
          <div className={styles.nameWrapper}>
            <input
              className={styles.input}
              type="text"
              id="fname"
              name="firstname"
              placeholder="Your name.."
              required
            />

            <input
              className={styles.input}
              type="text"
              id="lname"
              name="lastname"
              placeholder="Your last name.."
              required
            />
          </div>

          <div className={styles.nameWrapper}>
            <input
              className={styles.input}
              type="email"
              id="email"
              name="email"
              placeholder="Your email.."
              required
            />

            <select className={styles.select}>
              <option>Italia</option>
              <option>Russia</option>
              <option>Francia</option>
              <option>USA</option>
            </select>
          </div>

          <div className={styles.nameWrapper}>
            <textarea
              className={styles.textarea}
              id="subject"
              name="subject"
              placeholder="Write something.."
            ></textarea>
          </div>

          <button className={styles.arrowBtn}>Send</button>
        </form>
      </div>
    </div>
  );
}
