import Head from "next/head";
import { useRouter } from "next/router";
import styles from "./[id].module.scss";
import { Details } from "../../../components/Details/details";
import { Price } from "../../../components/Price/price";
import { GalleryCityPage } from "../../../components/GalleryCityPage/galleriCityPage";
import { GalleryCityPageSkeleton } from "../../../components/GalleryCityPageSkeleton/galleriCityPageSkeleton";

import { useVacationContext } from "../../../Context/Provider";
import Map from "../../../components/Map/Map";
import { useEffect, useState } from "react";
import { Activities } from "../../../components/Activities/activities";

const DynamicCity = () => {
  const [city, setCity] = useState();
  const [long, setLong] = useState();
  const [lat, setLat] = useState();
  const router = useRouter();
  const { id } = router.query;

  const {
    fetchAll,
    state: { vacation, loading },
  } = useVacationContext();

  const par = "/cities";
  useEffect(() => {
    fetchAll(par);
  }, []);

  useEffect(() => {
    const citys = vacation?.filter((element) =>
      element?.name.toLowerCase()?.includes(id.toLowerCase())
    );
    setLong(citys[0]?.longitude);
    setLat(citys[0]?.latitude);
    setCity(citys);
  }, [id, vacation]);

  return (
    <div className={styles.DynamicCountry}>
      <Head>
        <title>{id}</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.png" />
      </Head>

      <section className={styles.GalleryCityPageContainer}>
        {loading ? <GalleryCityPageSkeleton /> : <GalleryCityPage id={id} />}
      </section>
      <section className={styles.dettailsContainer}>
        <h1 className={styles.cityName}>{id}</h1>
        <Details />
      </section>

      <section className={styles.mapContainer}>
        <Map lng={long} lat={lat} />
      </section>
      <section>
        {city !== undefined && city.length !== 0 ? (
          <Activities render={city} />
        ) : (
          ""
        )}
      </section>
    </div>
  );
};

export default DynamicCity;
