export const FETCH_ALL_VACATION_REQUEST = 'FETCH_ALL_VACATION_REQUEST'
export const FETCH_ALL_VACATION_SUCCESS = 'FETCH_ALL_VACATION_SUCCESS'
export const FETCH_ALL_VACATION_ERROR = 'FETCH_ALL_VACATION_ERROR'
