import { AboutUs } from "../../components/Aboutus/aboutus";
import Head from "next/head";

const About = () => {
  return <>
 <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.png" />
      </Head>

  <AboutUs />;
  </>
};

export default About;
