import { AboutUs } from "../../components/Aboutus/aboutus";
import Head from "next/head";

const About = () => {
  return <>
 <Head>
        <title>Ferdast.com</title>
        <meta name="description" content="Generated by create next app" />
        <link
          href="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.css"
          rel="stylesheet"
        />

        <link rel="icon" href="/favicon.png" />
      </Head>

  <AboutUs />;
  </>
};

export default About;
