import Head from "next/head";
import { Hero } from "../components/Hero/hero";
import Navbar from "../components/Navbar";
import styles from "../styles/Home.module.css";
import { CardList } from "../components/CardList/cardList";
import { useEffect } from "react";
import { useVacationContext } from "../Context/Provider";

export default function Home() {
  const {
    fetchAll,
    state: { vacation, italia, spagna, francia, romania },
  } = useVacationContext();

  useEffect(() => {
    fetchAll("/cities");
  }, []);
  
  useEffect(() => {
    console.log("vacation",vacation);
    console.log("ita:",italia);
    console.log("spa:",spagna);
    console.log("fra:",francia);
    console.log("rom:",romania);
  }, [vacation]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Ferdast.com</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
          integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ=="
          crossorigin="anonymous"
          referrerpolicy="no-referrer"
        /> */}
      </Head>
      <Navbar />
      <Hero />
      <CardList />
    </div>
  );
}
